# Generated by Django 3.0.1 on 2020-08-20 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('working_years', models.IntegerField(blank=True, default=0, null=True)),
                ('implementations', models.IntegerField(blank=True, default=0, null=True)),
                ('supports', models.IntegerField(blank=True, default=0, null=True)),
                ('modules', models.IntegerField(blank=True, default=0, null=True)),
                ('industries', models.IntegerField(blank=True, default=0, null=True)),
                ('methodology', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.CharField(blank=True, default=None, max_length=60, null=True)),
            ],
        ),
    ]
