MODULES_LIST = (
    ('ABAP', 'ABAP'),
    ('APO', 'APO: ADVANCED PLANNER AND OPTIMIZER'),
    ('ARIBA', 'ARIBA'),
    ('LUMIRA', 'BO/LUMIRA/SAC'),
    ('BPC', 'BPC: BUSINESS PLANNING CONSOLIDATION'),
    ('BW', 'BW: BUSINESS WAREHOUSE'),
    ('CO', 'CO: CONTROLE'),
    ('CS', 'CS: CUSTOMER SERVICE'),
    ('DIRETOR', 'Diretor de projetos e programas'),
    ('EWM', 'EWM: EXTENDED WAREHOUSE MANAGEMENT'),
    ('FI', 'FI: CONTABILIDADE FINANCEIRA'),
    ('FIORI', 'FIORI'),
    ('GESTOR', 'GESTOR DE PROJETOS E PROGRAMAS'),
    ('GRC', 'GRC: GOVERNANCE, RISK AND COMPLIANCE'),
    ('GTS', 'GTS: GLOBAL TRADE MANAGEMENTE'),
    ('HCM', 'HCM: GESTÃO DO CAPITAL HUMANO'),
    ('HYBRID', 'HYBRIDS'),
    ('IBP', 'IBP: INTEGRATED BUSINESS PLANNING'),
    ('IDM', 'IDM: IDENTITY MANAGEMENT'),
    ('IM', 'IM: GESTÃO DOS INVESTIMENTOS'),
    ('LO', 'LO: GESTÃO GERAL DA LOGÍTICA'),
    ('MDM', 'MDM: MASTER DATA GOVERNACE'),
    ('MM', 'MM: ADMINISTRAÇÃO DE MATERIAIS'),
    ('OS', 'OS: GESTÃO DE PROJETOS'),
    ('PO', 'PO: PROCESS ORCHESTRATION'),
    ('PP', 'PP: PLANEJAMENTO DE PRODUÇÃO'),
    ('QM', 'QM: GESTÃO DA QUALIDADE'),
    ('SD', 'SD: VENDAS E DISTRIBUIÇÃO'),
    ('SFSF', 'SFSF: SUCCESS FACTORS'),
    ('SOLMAN', 'SOLMAN: SOLUTION MANAGER'),
    ('TRM', 'TRM: GESTÃO DOS RISCOS E TESOURARIA'),
    ('UI5', 'UI5: UX'),
    ('VISTEX', 'VISTEX'),
    ('WEBDYNPRO', 'WEBDYNPRO'),
    ('WF', 'WF: WORFFLOW'),
    ('WM', 'WM: GESTÃO DE INVENTÁRIO'),
)

INDUSTRIES_LIST = (
    ('AEROSPACE', 'Aerospace & Defense'),
    ('AUTOMOTIVE', 'Automotive'),
    ('BANKING', 'Banking'),
    ('CHEMICALS', 'Chemicals'),
    ('CONSUMER', 'Consumer Products'),
    ('DEFENSE', 'Defense & Security'),
    ('ENGINEERING', 'Engineering, Construction and Operations'),
    ('HEALTHCARE', 'Healthcare'),
    ('HIGHTECH', 'High Tech'),
    ('RESEARCH', 'Higher Education & Research'),
    ('INDUSTRIAL', 'Industrial Machinery and Components'),
    ('INSURANCE', 'Insurance'),
    ('LIFE_SCIENCES', 'Life Sciences'),
    ('MEDIA', 'Media'),
    ('MILL_PRODUCTS', 'Mill Products'),
    ('MINING', 'Mining'),
    ('OIL_GAS', 'Oil & Gas'),
    ('PHARMA', 'Pharma'),
    ('PROFESSIONAL_SERVICES', 'Professional Services'),
    ('PUBLIC_SECTOR', 'Public Sector'),
    ('RETAIL', 'Retail'),
    ('TELECOM', 'Telecommunications'),
    ('TRANSPORTATION', 'Transportation & Logistics'),
    ('UTILITIES', 'Utilities'),
    ('WHOLESALE_DISTRIBUTION', 'Wholesale Distribution'),
)

METHODOLOGY_LIST = (
    ('ASAP', 'ASAP'),
    ('ACTIVATE', 'SAP ACTIVATE'),
)