# Generated by Django 3.0.1 on 2020-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
    ]
