# Generated by Django 3.0.1 on 2020-08-20 23:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Headhunter',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tokens', models.IntegerField(default=2, editable=False)),
                ('tokens_total', models.IntegerField(default=2, editable=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, null=True)),
                ('working_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(38)])),
                ('implementations', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(38)])),
                ('supports', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(38)])),
                ('modules', models.CharField(blank=True, choices=[('ABAP', 'ABAP'), ('APO', 'APO: ADVANCED PLANNER AND OPTIMIZER'), ('ARIBA', 'ARIBA'), ('LUMIRA', 'BO/LUMIRA/SAC'), ('BPC', 'BPC: BUSINESS PLANNING CONSOLIDATION'), ('BW', 'BW: BUSINESS WAREHOUSE'), ('CO', 'CO: CONTROLE'), ('CS', 'CS: CUSTOMER SERVICE'), ('DIRETOR', 'Diretor de projetos e programas'), ('EWM', 'EWM: EXTENDED WAREHOUSE MANAGEMENT'), ('FI', 'FI: CONTABILIDADE FINANCEIRA'), ('FIORI', 'FIORI'), ('GESTOR', 'GESTOR DE PROJETOS E PROGRAMAS'), ('GRC', 'GRC: GOVERNANCE, RISK AND COMPLIANCE'), ('GTS', 'GTS: GLOBAL TRADE MANAGEMENTE'), ('HCM', 'HCM: GESTÃO DO CAPITAL HUMANO'), ('HYBRID', 'HYBRIDS'), ('IBP', 'IBP: INTEGRATED BUSINESS PLANNING'), ('IDM', 'IDM: IDENTITY MANAGEMENT'), ('IM', 'IM: GESTÃO DOS INVESTIMENTOS'), ('LO', 'LO: GESTÃO GERAL DA LOGÍTICA'), ('MDM', 'MDM: MASTER DATA GOVERNACE'), ('MM', 'MM: ADMINISTRAÇÃO DE MATERIAIS'), ('OS', 'OS: GESTÃO DE PROJETOS'), ('PO', 'PO: PROCESS ORCHESTRATION'), ('PP', 'PP: PLANEJAMENTO DE PRODUÇÃO'), ('QM', 'QM: GESTÃO DA QUALIDADE'), ('SD', 'SD: VENDAS E DISTRIBUIÇÃO'), ('SFSF', 'SFSF: SUCCESS FACTORS'), ('SOLMAN', 'SOLMAN: SOLUTION MANAGER'), ('TRM', 'TRM: GESTÃO DOS RISCOS E TESOURARIA'), ('UI5', 'UI5: UX'), ('VISTEX', 'VISTEX'), ('WEBDYNPRO', 'WEBDYNPRO'), ('WF', 'WF: WORFFLOW'), ('WM', 'WM: GESTÃO DE INVENTÁRIO')], max_length=200, null=True)),
                ('industries', models.CharField(blank=True, choices=[('AEROSPACE', 'Aerospace & Defense'), ('AUTOMOTIVE', 'Automotive'), ('BANKING', 'Banking'), ('CHEMICALS', 'Chemicals'), ('CONSUMER', 'Consumer Products'), ('DEFENSE', 'Defense & Security'), ('ENGINEERING', 'Engineering, Construction and Operations'), ('HEALTHCARE', 'Healthcare'), ('HIGHTECH', 'High Tech'), ('RESEARCH', 'Higher Education & Research'), ('INDUSTRIAL', 'Industrial Machinery and Components'), ('INSURANCE', 'Insurance'), ('LIFE_SCIENCES', 'Life Sciences'), ('MEDIA', 'Media'), ('MILL_PRODUCTS', 'Mill Products'), ('MINING', 'Mining'), ('OIL_GAS', 'Oil & Gas'), ('PHARMA', 'Pharma'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('PUBLIC_SECTOR', 'Public Sector'), ('RETAIL', 'Retail'), ('TELECOM', 'Telecommunications'), ('TRANSPORTATION', 'Transportation & Logistics'), ('UTILITIES', 'Utilities'), ('WHOLESALE_DISTRIBUTION', 'Wholesale Distribution')], max_length=120, null=True)),
                ('methodology', models.CharField(blank=True, choices=[('ASAP', 'ASAP'), ('ACTIVATE', 'SAP ACTIVATE')], max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('special_status', 'Can access headhunter data')],
            },
        ),
    ]
